[2024-04-29T15:57:22.878+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-29T15:57:22.956+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL-VNExpress.transform_data manual__2024-04-29T08:56:47.578775+00:00 [queued]>
[2024-04-29T15:57:22.970+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL-VNExpress.transform_data manual__2024-04-29T08:56:47.578775+00:00 [queued]>
[2024-04-29T15:57:22.971+0700] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-29T15:57:23.012+0700] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): transform_data> on 2024-04-29 08:56:47.578775+00:00
[2024-04-29T15:57:23.019+0700] {standard_task_runner.py:63} INFO - Started process 44545 to run task
[2024-04-29T15:57:23.026+0700] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ETL-VNExpress', 'transform_data', 'manual__2024-04-29T08:56:47.578775+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/scape_news.py', '--cfg-path', '/tmp/tmpxtnz3acm']
[2024-04-29T15:57:23.027+0700] {standard_task_runner.py:91} INFO - Job 3: Subtask transform_data
[2024-04-29T15:57:23.146+0700] {task_command.py:426} INFO - Running <TaskInstance: ETL-VNExpress.transform_data manual__2024-04-29T08:56:47.578775+00:00 [running]> on host DESKTOP-BEALJ3H.
[2024-04-29T15:57:23.316+0700] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ETL-VNExpress' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-29T08:56:47.578775+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-29T08:56:47.578775+00:00'
[2024-04-29T15:57:23.318+0700] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-29T15:57:23.780+0700] {logging_mixin.py:188} INFO - (234, 6)
[2024-04-29T15:57:23.790+0700] {logging_mixin.py:188} WARNING - /mnt/d/Programming/Vietnamese-Text-Generator/airflow/plugins/clean_data.py:48 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2024-04-29T15:57:23.795+0700] {logging_mixin.py:188} WARNING - /mnt/d/Programming/Vietnamese-Text-Generator/airflow/plugins/clean_data.py:51 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2024-04-29T15:57:23.802+0700] {logging_mixin.py:188} WARNING - /mnt/d/Programming/Vietnamese-Text-Generator/airflow/plugins/clean_data.py:53 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2024-04-29T15:57:28.562+0700] {python.py:237} INFO - Done. Returned value was: (     article_id  ...                                        description
0             0  ...  Ban Chấp hành Trung ương khai trừ Đảng với ngu...
1             1  ...  Trung ương họp bất thường đồng ý cho ông Vương...
2             2  ...  Sáng 26/4, lãnh đạo Đảng, Nhà nước đặt v...
3             3  ...  Hà NộiTheo Bộ trưởng Thông tin và Truyền thông...
4             4  ...  Nguyên Chủ tịch tỉnh An Giang Vương Bình Thạnh...
..          ...  ...                                                ...
229         229  ...  Xe chạy bằng điện, mỗi ôtô 8 chỗ chở khách tha...
230         230  ...  Tuyến đường sắt mới Lào Cai - Hà Nội - Quảng N...
231         231  ...  Dự án nâng cấp đường Tạ Quang Bửu, quận 8, dài...
232         232  ...  Dựa trên định hướng điều chỉnh quy hoạch TP HC...
233         233  ...  Bộ Giao thông Vận tải kiến nghị Chính phủ nâng...

[234 rows x 6 columns],      article_id    topic   sub-topic                                                tag
0             0  thoi-su   chinh-tri  trung_ương đánh_giá ông chữ suy_thoái về tư_tư...
1             1  thoi-su   chinh-tri  thông_tin văn_phòng trung_ương đảng phát hội_n...
2             2  thoi-su   chinh-tri  đoàn đại_biểu ban chấp_hành trung_ương đảng , ...
3             3  thoi-su   chinh-tri  hội_nghị phát_triển nguồn nhân_lực phục_vụ côn...
4             4  thoi-su   chinh-tri  kỳ họp 40 ( ngày 23 - 24 / 4 ) , ủy_ban kiểm_t...
..          ...      ...         ...                                                ...
229         229  thoi-su  giao-thong  hệ_thống xe điện công_ty_tnhh saigon public tr...
230         230  thoi-su  giao-thong  cục đường_sắt việt_nam ( bộ giao_thông vận_tải...
231         231  thoi-su  giao-thong  chiều 10 / 4 , hơn chục công_nhân loại xe_lu ,...
232         232  thoi-su  giao-thong  đề_xuất đưa cuộc họp về xây_dựng đề_án phát_tr...
233         233  thoi-su  giao-thong  bộ giao_thông vận_tải ngày 9 / 4 đề_xuất phươn...

[234 rows x 4 columns])
[2024-04-29T15:57:28.611+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-29T15:57:28.625+0700] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/mnt/d/Programming/Vietnamese-Text-Generator/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 486, in _execute_task
    task_instance.xcom_push(key=XCOM_RETURN_KEY, value=xcom_value, session=session)
  File "/mnt/d/Programming/Vietnamese-Text-Generator/airflow_env/lib/python3.10/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/mnt/d/Programming/Vietnamese-Text-Generator/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in xcom_push
    XCom.set(
  File "/mnt/d/Programming/Vietnamese-Text-Generator/airflow_env/lib/python3.10/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/mnt/d/Programming/Vietnamese-Text-Generator/airflow_env/lib/python3.10/site-packages/airflow/models/xcom.py", line 247, in set
    value = cls.serialize_value(
  File "/mnt/d/Programming/Vietnamese-Text-Generator/airflow_env/lib/python3.10/site-packages/airflow/models/xcom.py", line 675, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/mnt/d/Programming/Vietnamese-Text-Generator/airflow_env/lib/python3.10/site-packages/airflow/utils/json.py", line 102, in encode
    o = self.default(o)
  File "/mnt/d/Programming/Vietnamese-Text-Generator/airflow_env/lib/python3.10/site-packages/airflow/utils/json.py", line 91, in default
    return serialize(o)
  File "/mnt/d/Programming/Vietnamese-Text-Generator/airflow_env/lib/python3.10/site-packages/airflow/serialization/serde.py", line 150, in serialize
    return encode(classname or serialized_classname, version, serialize(data, depth + 1))
  File "/mnt/d/Programming/Vietnamese-Text-Generator/airflow_env/lib/python3.10/site-packages/airflow/serialization/serde.py", line 127, in serialize
    return [serialize(d, depth + 1) for d in o]
  File "/mnt/d/Programming/Vietnamese-Text-Generator/airflow_env/lib/python3.10/site-packages/airflow/serialization/serde.py", line 127, in <listcomp>
    return [serialize(d, depth + 1) for d in o]
  File "/mnt/d/Programming/Vietnamese-Text-Generator/airflow_env/lib/python3.10/site-packages/airflow/serialization/serde.py", line 148, in serialize
    data, serialized_classname, version, is_serialized = _serializers[qn].serialize(o)
  File "/mnt/d/Programming/Vietnamese-Text-Generator/airflow_env/lib/python3.10/site-packages/airflow/serialization/serializers/pandas.py", line 40, in serialize
    import pyarrow as pa
ModuleNotFoundError: No module named 'pyarrow'
[2024-04-29T15:57:28.663+0700] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=ETL-VNExpress, task_id=transform_data, execution_date=20240429T085647, start_date=20240429T085722, end_date=20240429T085728
[2024-04-29T15:57:28.699+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task transform_data (No module named 'pyarrow'; 44545)
[2024-04-29T15:57:28.742+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-29T15:57:28.787+0700] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-29T15:57:28.818+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
