[2024-04-29T16:28:36.464+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-29T16:28:36.569+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL-VNExpress.transform_data manual__2024-04-29T09:28:00.114395+00:00 [queued]>
[2024-04-29T16:28:36.594+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL-VNExpress.transform_data manual__2024-04-29T09:28:00.114395+00:00 [queued]>
[2024-04-29T16:28:36.595+0700] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-29T16:28:36.637+0700] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): transform_data> on 2024-04-29 09:28:00.114395+00:00
[2024-04-29T16:28:36.645+0700] {standard_task_runner.py:63} INFO - Started process 53207 to run task
[2024-04-29T16:28:36.652+0700] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ETL-VNExpress', 'transform_data', 'manual__2024-04-29T09:28:00.114395+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/scape_news.py', '--cfg-path', '/tmp/tmps05e0zzg']
[2024-04-29T16:28:36.654+0700] {standard_task_runner.py:91} INFO - Job 9: Subtask transform_data
[2024-04-29T16:28:36.767+0700] {task_command.py:426} INFO - Running <TaskInstance: ETL-VNExpress.transform_data manual__2024-04-29T09:28:00.114395+00:00 [running]> on host DESKTOP-BEALJ3H.
[2024-04-29T16:28:36.911+0700] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ETL-VNExpress' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-29T09:28:00.114395+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-29T09:28:00.114395+00:00'
[2024-04-29T16:28:36.913+0700] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-29T16:28:37.361+0700] {logging_mixin.py:188} WARNING - /mnt/d/Programming/Vietnamese-Text-Generator/airflow/plugins/clean_data.py:53 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2024-04-29T16:28:37.367+0700] {logging_mixin.py:188} WARNING - /mnt/d/Programming/Vietnamese-Text-Generator/airflow/plugins/clean_data.py:56 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2024-04-29T16:28:37.376+0700] {logging_mixin.py:188} WARNING - /mnt/d/Programming/Vietnamese-Text-Generator/airflow/plugins/clean_data.py:58 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2024-04-29T16:28:41.023+0700] {python.py:237} INFO - Done. Returned value was: None
[2024-04-29T16:28:41.024+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-29T16:28:41.035+0700] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=ETL-VNExpress, task_id=transform_data, execution_date=20240429T092800, start_date=20240429T092836, end_date=20240429T092841
[2024-04-29T16:28:41.082+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-29T16:28:41.133+0700] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-29T16:28:41.145+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
