[2024-04-29T16:13:13.340+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-29T16:13:13.432+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL-VNExpress.transform_data manual__2024-04-29T09:12:41.744633+00:00 [queued]>
[2024-04-29T16:13:13.447+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL-VNExpress.transform_data manual__2024-04-29T09:12:41.744633+00:00 [queued]>
[2024-04-29T16:13:13.448+0700] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-29T16:13:13.483+0700] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): transform_data> on 2024-04-29 09:12:41.744633+00:00
[2024-04-29T16:13:13.489+0700] {standard_task_runner.py:63} INFO - Started process 48933 to run task
[2024-04-29T16:13:13.493+0700] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ETL-VNExpress', 'transform_data', 'manual__2024-04-29T09:12:41.744633+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/scape_news.py', '--cfg-path', '/tmp/tmpivw4caiv']
[2024-04-29T16:13:13.495+0700] {standard_task_runner.py:91} INFO - Job 6: Subtask transform_data
[2024-04-29T16:13:13.590+0700] {task_command.py:426} INFO - Running <TaskInstance: ETL-VNExpress.transform_data manual__2024-04-29T09:12:41.744633+00:00 [running]> on host DESKTOP-BEALJ3H.
[2024-04-29T16:13:13.751+0700] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ETL-VNExpress' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-29T09:12:41.744633+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-29T09:12:41.744633+00:00'
[2024-04-29T16:13:13.753+0700] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-29T16:13:14.216+0700] {logging_mixin.py:188} INFO - (234, 6)
[2024-04-29T16:13:14.227+0700] {logging_mixin.py:188} WARNING - /mnt/d/Programming/Vietnamese-Text-Generator/airflow/plugins/clean_data.py:50 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2024-04-29T16:13:14.232+0700] {logging_mixin.py:188} WARNING - /mnt/d/Programming/Vietnamese-Text-Generator/airflow/plugins/clean_data.py:53 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2024-04-29T16:13:14.240+0700] {logging_mixin.py:188} WARNING - /mnt/d/Programming/Vietnamese-Text-Generator/airflow/plugins/clean_data.py:55 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2024-04-29T16:13:17.769+0700] {python.py:237} INFO - Done. Returned value was: None
[2024-04-29T16:13:17.770+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-29T16:13:17.783+0700] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=ETL-VNExpress, task_id=transform_data, execution_date=20240429T091241, start_date=20240429T091313, end_date=20240429T091317
[2024-04-29T16:13:17.843+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-29T16:13:17.888+0700] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-29T16:13:17.902+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
